### ISSUE TITLE
New Transactions Quantity are Same

### ISSUE THREAD

**Issue by sikandarkhan33** [amirsanni/Mini-Inventory-and-Sales-Management-System#21]
Dear Brother,
I just experimenting with your project. There is a bug in the 
transaction. When you add a new item to transaction. The item name is changed but the remaining quantity and the price is shown same as the first item. 
(Pins available qty =15 & price/Unit = 100) (watch available qty=20 & price/unit=300)
Need your guidance please.
Note: Screenshot attached.
![untitled](https://user-images.githubusercontent.com/10974944/33885821-4deae472-df66-11e7-80b7-acfe79e6afff.png)

**Comment by amirsanni** [comment]
Oh! Thanks.

I updated that module today. Will look into it and update it ASAP.

Thank you

On 12 Dec 2017 2:03 pm, "sikandarkhan33" <notifications@github.com> wrote:

Dear Brother,
I just experimenting with your project. There is a bug in the
transaction. When you add a new item to transaction. The item name is
changed but the remaining quantity and the price is shown same as the first
item.
(Pins available qty =15 & price/Unit = 100) (watch available qty=20 &
price/unit=300)
Need your guidance please.
Note: Screenshot attached.
[image: untitled]
<https://user-images.githubusercontent.com/10974944/33885821-4deae472-df66-11e7-80b7-acfe79e6afff.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/amirsanni/Mini-Inventory-and-Sales-Management-System/issues/21>,
or mute the thread

**Comment by amirsanni** [comment]
Hi, when did you do this test? I noticed the bug and earlier today and I have fixed it. Occurred after a change I made few days ago. Please test again on the **demo** page because I just did and it worked fine.

**Comment by amirsanni** [comment]
You might need to re-download it OR just fix it on your end.

Open **Application**=>**Models**=>**Item.php** and modify `function getItemInfo`.

```
public function getItemInfo($where_clause, $fields_to_fetch){
        $this->db->select($fields_to_fetch);
        
        $this->db->where($where_clause);
        
        $run_q = $this->db->get('items');
        
        return $run_q->num_rows() ? $run_q->row() : FALSE;
    }
```

**Comment by sikandarkhan33** [comment]
Dear amir,
Thank you for your precious time and quick reply. The bug is fixed now. 
i have one more question. The bar code scanner button is not working. Is there a driver or something to install it or just plug the bar code scanner to the computer and it work. Please guide me.

**Comment by amirsanni** [comment]
Welcome.

Once your device recognises the barcode scanner, click on the **Use Barcode Scanner** button so as to focus the mouse in the input field that will read the result from the scanner. Any driver installation has nothing to do with the app but your device.

**Comment by sikandarkhan33** [comment]
Thanks Brother, i got it. if there is any bug i seen in the future i will text you.
I have some suggestion for your app. if these functions also include in the app then it will be a best web app for sales and inventory management.

1- Add a exchange and return items fields in the transaction. (e.g if a customer want to exchange or return the inventory it should be deducted from the customer previous bill and the items will be automatically added to the inventory and also the invoice/bill should be updated.)
2- Add a purchasing price & sales price fields to the new items inventory page. it should reflect the margin in the dashboard that how much profit is gain from the sales.

If there is anything i can do for you please feel free to ask.
Regards.

**Comment by amirsanni** [comment]
Thanks @sikandarkhan33.

I actually have no plan to improve on this due to time constraint but I'll consider rebuilding the whole thing with a new design and include these features if I have the time.

Thank you once again.
