### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [amirsanni/Mini-Inventory-and-Sales-Management-System#82]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by amirsanni** [comment]
`SECURITY.md` file created.

**Comment by JamieSlome** [comment]
@amirsanni - would you be able to take a look at this report:

https://huntr.dev/bounties/1d84931c-ee10-4944-9764-d96612cdbc71/

**Comment by JamieSlome** [comment]
@amirsanni - just wanted to check in one last time on:
https://huntr.dev/bounties/1d84931c-ee10-4944-9764-d96612cdbc71/

It has been 3 months since the point of disclosure, and we have not heard anything back from you. We will give it one more week, and then make the disclosure public so that members of your community are able to respond to the potential issue.

Let me know if you have any questions! ❤️
